
1. Preprocessing data containing 29963 samples...
---> Data Preprocessing done!
---> Total number of preprocessed & unrejected crop samples: 26859
2. Training and tuning model.....
--->Validation on 14 fns done! Best harmonic_mean of precision on validation data is 0.9558417979471787
--->Validation on 13 fns done! Best harmonic_mean of precision on validation data is 0.9532008424849558
--->Model training and tuning done!
3. Evaluating the best models on test data....
Traceback (most recent call last):
  File "/Users/sreekrishna/Krishi_DSS/KDSS_ML/pipepine.py", line 50, in run_experiment
    wandb.log(wandb.Table(dataframe=test_reports[0]))
  File "/Users/sreekrishna/miniconda3/envs/krishna/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sreekrishna/miniconda3/envs/krishna/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/sreekrishna/miniconda3/envs/krishna/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sreekrishna/miniconda3/envs/krishna/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1828, in log
    self._log(data=data, step=step, commit=commit)
  File "/Users/sreekrishna/miniconda3/envs/krishna/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1591, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary