Traceback (most recent call last):
  File "/scratchi/KDSS/kdss_ml/pipepine.py", line 16, in run_experiment
    preprocessed_data, _ = rabi_data_preprocess(preprocess_dict['input_path'])
  File "/scratchi/KDSS/kdss_ml/src/crop_type_classification/preprocess.py", line 28, in rabi_data_preprocess
    data = raw_data[rabi_fns]
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1456, in __getitem__
    result = super().__getitem__(key)
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/frame.py", line 4096, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6199, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6251, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['crop_type'] not in index"